<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#导入相关的包" data-toc-modified-id="导入相关的包-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>导入相关的包</a></span></li><li><span><a href="#导入相关数据" data-toc-modified-id="导入相关数据-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>导入相关数据</a></span></li><li><span><a href="#特征提取" data-toc-modified-id="特征提取-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>特征提取</a></span><ul class="toc-item"><li><span><a href="#是否在正常值范围内" data-toc-modified-id="是否在正常值范围内-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>是否在正常值范围内</a></span></li></ul></li></ul></div>

# 导入相关的包

In [123]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

# 导入相关数据

In [130]:
%time
trains = pd.read_csv('../clean_data/base_train.csv',encoding="gbk")
test = pd.read_csv('../clean_data/test.csv',encoding='gbk')
vals = pd.read_csv('../clean_data/model_fill_train.csv',encoding='gbk')
all_data = pd.concat([trains, vals, test],axis=0,ignore_index=True)

Wall time: 0 ns

In [115]:
trains.shape
test.shape
vals.shape
all_data.shape

(3911, 38)

(1000, 36)

(1695, 38)

(6606, 38)

In [68]:
all_data.head()

,age,blood_sugar,blood_sugar_log,date,feature_0,feature_1,feature_10,feature_11,feature_12,feature_13,...,feature_35,feature_36,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,gender,id
0,41,6.06,0.529777,12/10/2017,24.96,23.10,1.37,2.65,5.87,77.25,...,4.7,0.6,76.88,49.60,27.28,1.82,1.31,4.43,1,1
1,41,5.39,0.651054,19/10/2017,24.57,36.25,0.93,2.63,5.26,87.12,...,4.7,0.8,79.43,47.76,31.67,1.51,2.81,4.06,1,2
2,46,5.59,0.610842,26/10/2017,20.82,15.23,1.64,2.01,4.77,78.19,...,3.2,0.8,86.23,48.00,38.23,1.26,0.99,4.13,1,3
3,22,4.30,0.974218,25/10/2017,14.99,10.59,1.43,5.04,4.23,61.46,...,4.6,0.5,70.98,44.02,26.96,1.63,1.06,6.89,0,4
4,74,5.97,0.544044,18/10/2017,23.72,22.59,1.81,4.28,6.11,66.66,...,2.1,1.0,76.46,45.85,30.61,1.50,2.45,6.65,0,6

# 特征提取

## 是否在正常值范围内

In [69]:
all_data.columns
all_data

Index(['age', 'blood_sugar', 'blood_sugar_log', 'date', 'feature_0',
       'feature_1', 'feature_10', 'feature_11', 'feature_12', 'feature_13',
       'feature_14', 'feature_2', 'feature_20', 'feature_21', 'feature_22',
       'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27',
       'feature_28', 'feature_29', 'feature_3', 'feature_30', 'feature_31',
       'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36',
       'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8',
       'feature_9', 'gender', 'id'],
      dtype='object')

,age,blood_sugar,blood_sugar_log,date,feature_0,feature_1,feature_10,feature_11,feature_12,feature_13,...,feature_35,feature_36,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,gender,id
0,41,6.06,0.529777,12/10/2017,24.960,23.100,1.370,2.650,5.870,77.250,...,4.7,0.6,76.880,49.600,27.280,1.820,1.310,4.430,1,1
1,41,5.39,0.651054,19/10/2017,24.570,36.250,0.930,2.630,5.260,87.120,...,4.7,0.8,79.430,47.760,31.670,1.510,2.810,4.060,1,2
2,46,5.59,0.610842,26/10/2017,20.820,15.230,1.640,2.010,4.770,78.190,...,3.2,0.8,86.230,48.000,38.230,1.260,0.990,4.130,1,3
3,22,4.30,0.974218,25/10/2017,14.990,10.590,1.430,5.040,4.230,61.460,...,4.6,0.5,70.980,44.020,26.960,1.630,1.060,6.890,0,4
4,74,5.97,0.544044,18/10/2017,23.720,22.590,1.810,4.280,6.110,66.660,...,2.1,1.0,76.460,45.850,30.610,1.500,2.450,6.650,0,6
5,31,5.11,0.714748,21/09/2017,24.970,25.530,1.330,3.820,6.140,95.980,...,3.1,0.7,80.820,46.400,34.420,1.350,1.510,5.600,1,7
6,55,5.94,0.548920,21/09/2017,37.320,40.030,1.280,4.200,6.310,92.160,...,2.8,0.9,74.170,41.630,32.540,1.280,1.320,5.920,1,8
7,39,5.66,0.597658,16/10/2017,21.700,39.170,1.510,3.600,4.980,78.570,...,3.3,0.4,76.120,49.310,26.810,1.840,2.070,5.500,1,9
8,35,5.48,0.632470,10/10/2017,18.890,15.790,1.550,2.020,6.610,86.880,...,1.0,0.7,75.940,46.640,29.300,1.590,1.250,3.980,0,10
9,47,4.44,0.918255,13/10/2017,27.330,35.760,0.900,2.840,5.600,66.490,...,1.3,0.9,75.840,43.710,32.130,1.360,1.960,4.320,1,11
10,50,5.48,0.632470,10/10/2017,22.890,28.460,1.140,2.650,4.690,74.530,...,1.2,0.4,73.800,48.320,25.480,1.900,3.320,4.470,1,12
11,48,5.32,0.666105,19/10/2017,30.110,34.700,1.430,1.940,4.390,67.540,...,4.2,1.3,77.860,43.050,34.810,1.240,1.210,3.690,0,13
12,36,5.08,0.722165,11/10/2017,16.820,11.800,1.930,0.560,3.470,73.260,...,0.6,0.3,76.840,47.560,29.280,1.620,0.270,2.850,0,14
13,37,4.63,0.851118,27/09/2017,24.580,24.640,1.210,3.550,3.460,65.990,...,1.5,0.8,92.310,46.980,45.330,1.040,1.220,5.200,0,15
14,43,4.92,0.763972,28/09/2017,20.070,14.810,1.580,3.520,5.670,62.260,...,1.1,0.5,74.430,44.490,29.940,1.490,1.520,5.510,0,16
15,77,7.08,0.398163,24/10/2017,18.490,17.290,1.020,2.490,10.680,134.630,...,1.9,0.4,76.020,42.390,33.630,1.260,4.590,4.050,1,17
16,42,4.66,0.841316,16/10/2017,24.710,30.260,1.110,4.070,6.770,90.660,...,1.0,0.2,81.870,43.850,38.020,1.150,3.870,5.830,1,18
17,39,6.58,0.456628,30/10/2017,31.440,43.970,1.110,3.400,4.750,107.330,...,3.5,0.8,79.740,46.490,33.250,1.400,1.330,4.550,1,19
18,38,4.29,0.978459,28/09/2017,23.580,31.190,1.200,4.290,3.070,94.160,...,1.3,0.4,81.500,51.160,30.340,1.690,2.630,5.930,1,20
19,30,4.55,0.878274,29/09/2017,33.250,67.190,1.180,4.020,3.790,103.150,...,2.0,0.6,82.800,49.320,33.480,1.470,3.440,5.500,1,21
20,51,5.16,0.702658,26/10/2017,26.530,20.440,1.360,2.810,4.250,98.690,...,2.4,0.3,75.700,48.680,27.020,1.800,1.870,4.480,1,22
21,38,5.13,0.709871,19/10/2017,24.130,34.020,1.730,2.710,3.560,65.550,...,4.3,0.7,76.120,44.870,31.250,1.440,1.420,4.780,0,23
22,33,4.37,0.945469,30/09/2017,15.770,11.430,1.220,1.970,5.930,65.040,...,1.1,0.4,83.110,47.370,35.740,1.330,0.940,3.490,0,24
23,28,5.17,0.700280,20/10/2017,20.240,12.550,1.920,2.450,4.270,71.370,...,0.8,0.6,76.970,47.890,29.080,1.650,0.600,4.880,0,25
24,34,4.64,0.847828,30/10/2017,20.890,16.160,1.470,4.370,4.360,68.110,...,0.3,0.6,77.070,43.720,33.350,1.310,1.400,5.930,0,26
25,34,5.82,0.569069,30/10/2017,32.030,52.740,1.680,4.130,6.200,80.230,...,1.1,0.6,79.110,50.400,28.710,1.760,1.180,5.930,1,27
26,38,6.29,0.495607,31/10/2017,34.620,54.430,1.120,3.920,4.000,88.320,...,1.9,0.8,78.470,49.260,29.210,1.690,2.460,5.370,1,28
27,60,5.10,0.717206,24/10/2017,28.360,32.300,1.530,2.690,8.250,78.720,...,1.7,0.8,71.380,43.210,28.170,1.530,0.920,4.590,1,29
28,55,5.41,0.646852,17/10/2017,29.600,34.070,1.250,3.580,5.330,88.480,...,2.6,1.2,82.330,45.490,36.840,1.230,1.620,5.280,1,30
29,56,5.48,0.632470,17/10/2017,22.680,16.930,2.070,2.850,3.660,68.160,...,1.8,0.4,73.750,47.420,26.330,1.800,0.690,5.410,1,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6576,57,NaN,NaN,20/10/2017,14.810,15.760,0.970,3.640,9.590,90.370,...,1.4,0.3,68.220,41.280,26.940,1.530,1.450,4.990,1,6739
6577,56,NaN,NaN,20/10/2017,18.050,18.200,1.410,3.310,4.640,91.670,...,2.1,0.4,80.890,50.000,30.890,1.620,1.300,5.020,1,6740
6578,55,NaN,NaN,20/10/2017,40.140,33.500,1.210,3.770,4.680,68.660,...,2.6,1.0,74.730,43.970,30.760,1.430,3.530,5.650,0,6741
6579,54,NaN,NaN,20/10/2017,26.210,44.900,0.870,3.230,7.290,70.870,...,5.3,0.6,76.370,47.320,29.050,1.630,2.570,4.440,1,6742
6580,54,NaN,NaN,20/10/2017,26.511,26.310,1.368,3.511,5.050,68.660,...,1.3,0.6,77.804,46.068,31.235,1.488,2.058,5.544,0,6743
6581,50,NaN,NaN,20/10/2017,16.970,11.350,1.690,4.510,2.620,56.570,...,4.1,0.6,79.220,46.430,32.790,1.420,1.740,6.540,0,6744
6582,55,NaN,NaN,20/10/2017,28.296,28.851,1.335,3.566,5.155,80.657,...,1.5,0.5,77.539,46.195,31.137,1.497,1.949,5.477,1,6745
6583,45,NaN,NaN,20/10/2017,28.400,28.140,1.290,4.330,3.740,81.510,...,0.8,0.3,75.300,43.700,31.600,1.380,1.010,6.020,1,6746
6584,60,NaN,NaN,20/10/2017,51.310,20.940,1.510,3.110,4.200,67.990,...,1.0,0.6,78.820,47.190,31.630,1.490,1.090,5.060,0,6747
6585,39,NaN,NaN,20/10/2017,19.270,11.060,1.610,3.460,4.380,61.770,...,1.4,0.4,72.440,43.430,29.010,1.500,0.970,5.390,0,6748
6586,60,NaN,NaN,20/10/2017,27.573,27.429,1.321,3.446,5.078,80.629,...,2.4,0.9,76.716,46.079,30.751,1.500,1.805,5.257,1,6749
6587,41,NaN,NaN,20/10/2017,21.800,11.070,1.930,1.700,5.000,66.320,...,1.0,1.0,75.610,46.380,29.230,1.590,0.660,4.050,0,6750
6588,60,NaN,NaN,20/10/2017,19.010,14.990,1.390,4.690,6.600,69.340,...,1.5,0.4,77.570,44.490,33.080,1.340,1.460,6.650,0,6751
6589,39,NaN,NaN,20/10/2017,15.700,10.180,1.730,3.300,3.330,64.600,...,0.3,0.4,80.350,47.190,33.160,1.420,1.100,5.490,0,6752
6590,53,NaN,NaN,20/10/2017,49.880,87.690,1.350,3.820,4.200,66.630,...,1.6,0.4,76.620,46.810,29.810,1.570,2.130,5.620,0,6753
6591,59,NaN,NaN,20/10/2017,27.898,25.448,1.790,3.920,5.019,73.687,...,2.1,0.7,76.814,45.576,31.051,1.486,1.610,6.250,0,6754
6592,46,NaN,NaN,20/10/2017,22.680,17.020,1.580,3.260,4.220,76.780,...,3.2,1.0,70.810,42.390,28.420,1.490,1.710,5.450,0,6755
6593,49,NaN,NaN,20/10/2017,26.150,23.400,1.560,4.320,5.390,67.310,...,1.1,0.3,74.540,44.560,29.980,1.490,2.990,6.400,0,6756
6594,59,NaN,NaN,20/10/2017,37.390,28.340,1.440,5.300,5.030,103.840,...,2.4,0.8,77.130,46.370,30.760,1.510,1.640,7.380,1,6757
6595,62,NaN,NaN,20/10/2017,26.975,26.363,1.324,3.570,5.194,80.891,...,1.5,0.3,77.555,45.701,31.457,1.477,1.926,5.462,1,6758
6596,66,NaN,NaN,20/10/2017,22.830,24.590,1.270,2.560,4.880,99.100,...,0.6,0.2,77.880,45.430,32.450,1.400,1.210,4.130,1,6759
6597,48,NaN,NaN,20/10/2017,20.830,14.510,2.690,3.130,3.620,61.120,...,0.7,0.2,80.520,48.850,31.670,1.540,0.890,6.030,0,6760
6598,43,NaN,NaN,20/10/2017,13.650,10.700,1.090,3.550,4.770,59.820,...,0.8,0.7,75.170,46.140,29.030,1.590,0.930,4.920,0,6761
6599,50,NaN,NaN,20/10/2017,35.860,47.610,1.250,4.480,8.520,75.430,...,1.2,0.7,77.000,43.880,33.120,1.320,3.900,6.470,0,6762
6600,54,NaN,NaN,20/10/2017,30.470,38.470,1.740,4.850,5.690,99.100,...,1.3,0.7,78.420,46.590,31.830,1.460,2.660,7.380,1,6763
6601,37,NaN,NaN,20/10/2017,26.381,28.026,1.440,3.330,5.680,95.720,...,0.6,0.4,77.511,46.682,30.967,1.510,1.970,5.260,1,6764
6602,73,NaN,NaN,20/10/2017,19.330,12.460,1.790,3.510,3.420,63.070,...,1.1,0.6,76.140,42.150,33.990,1.240,1.290,5.660,0,6765
6603,79,NaN,NaN,20/10/2017,18.500,13.240,1.380,3.800,4.690,104.510,...,1.5,0.5,80.060,48.160,31.900,1.510,1.700,5.540,1,6766
6604,39,NaN,NaN,20/10/2017,26.150,7.080,1.440,5.040,4.190,66.970,...,0.7,0.6,75.050,44.000,31.050,1.420,1.370,6.950,0,6767
6605,57,NaN,NaN,20/10/2017,25.837,23.163,1.429,3.508,5.062,73.118,...,4.8,0.4,76.237,45.137,31.112,1.480,1.754,5.522,0,6768

In [131]:
%time
all_data["feature_0_is_normal"] = all_data["feature_0"].apply(lambda x: 0 if x < 10 else (2 if x > 40 else 1))
all_data["feature_1_is_normal"] = all_data["feature_1"].apply(lambda x: 0 if x < 10 else (2 if x > 40 else 1))
all_data["feature_1_feature_0"] = round(all_data["feature_0"] / all_data['feature_1'],3)
all_data["feature_1_feature_0_is_normal"] = all_data["feature_1_feature_0"].apply(lambda x: 0 if x > 1 else 1)
all_data["feature_2_is_normal"] = all_data["feature_2"].apply(lambda x: 0 if x < 40 else (2 if x > 150 else 1))
all_data["feature_3_is_normal"] = all_data[["feature_3","gender"]].apply(lambda x: 
                                       (0 if x[0] < 11 else(2 if x[0] > 50 else 1)) if x[1] == 1 else (3 if x[0] < 7 else(5 if x[0] > 32 else 4)), 
                                       axis=1)
all_data["feature_4_is_normal"] = all_data["feature_4"].apply(lambda x: 0 if x < 60 else (2 if x > 80 else 1))
all_data["feature_5_is_normal"] = all_data["feature_5"].apply(lambda x: 0 if x < 40 else (2 if x > 55 else 1))
all_data["feature_6_is_normal"] = all_data["feature_6"].apply(lambda x: 0 if x < 20 else (2 if x > 30 else 1))
all_data["feature_8_is_normal"] = all_data["feature_8"].apply(lambda x: 0 if x < 0.42 else (2 if x > 1.82 else 1))
all_data["feature_9_is_normal"] = all_data["feature_9"].apply(lambda x: 0 if x < 2.9 else (2 if x > 6 else 1))
all_data["feature_10_is_normal"] = all_data["feature_10"].apply(lambda x: 0 if x < 1.16 else (2 if x > 1.55 else 1))
all_data["feature_10_gender_is_normal"] = all_data[["feature_10","gender"]].apply(lambda x:
                                       (0 if x[0] < 1.1 else 1) if x[1] == 1 else (2 if x[0] < 1.2 else 3),
                                       axis=1)
all_data["feature_11_is_normal"] = all_data["feature_11"].apply(lambda x: 0 if x < 2.84 else (2 if x > 3.12 else 1))
all_data["feature_10_feature_11"] = round(all_data["feature_11"] / all_data['feature_10'],3)
all_data["feature_12_is_normal"] = all_data["feature_12"].apply(lambda x: 0 if x < 1.7 else (2 if x > 8.3 else 1))
all_data["feature_13_is_normal"] = all_data[["feature_13","gender"]].apply(lambda x:
                                       (0 if x[0] < 53 else(2 if x[0] > 106 else 1)) if x[1] == 1 else (3 if x[0] < 44 else(5 if x[0] > 97 else 4)),
                                       axis=1)
all_data["feature_14_is_normal"] = all_data[["feature_14","gender"]].apply(lambda x:
                                       (0 if x[0] < 150 else(2 if x[0] > 416 else 1)) if x[1] == 1 else (3 if x[0] < 89 else(5 if x[0] > 357 else 4)),
                                       axis=1)
all_data["feature_14_gender_is_normal"] = all_data[["feature_14","gender"]].apply(lambda x:
                                       (0 if x[0] > 420 else 1) if x[1] == 1 else (2 if x[0] > 350 else 3),
                                       axis=1)
all_data["feature_20_is_normal"] = all_data["feature_20"].apply(lambda x: 0 if x < 4 else (2 if x > 10 else 1))
all_data["feature_21_is_normal"] = all_data[["feature_21","gender"]].apply(lambda x:
                                       (0 if x[0] < 4.0 else(2 if x[0] > 5.5 else 1)) if x[1] == 1 else (3 if x[0] < 3.5 else(5 if x[0] > 5.0 else 4)),
                                       axis=1)
all_data["feature_22_is_normal"] = all_data[["feature_22","gender"]].apply(lambda x:
                                       (0 if x[0] < 120 else(2 if x[0] > 160 else 1)) if x[1] == 1 else (3 if x[0] < 110 else(5 if x[0] > 150 else 4)),
                                       axis=1)
all_data["feature_23_is_normal"] = all_data[["feature_23","gender"]].apply(lambda x:
                                       (0 if x[0] < 0.4 else(2 if x[0] > 0.5 else 1)) if x[1] == 1 else (3 if x[0] < 0.37 else(5 if x[0] > 0.48 else 4)),
                                       axis=1)
all_data["feature_24_is_normal"] = all_data["feature_24"].apply(lambda x: 0 if x < 80 else (2 if x > 100 else 1))
all_data["feature_25_is_normal"] = all_data["feature_25"].apply(lambda x: 0 if x < 27 else (2 if x > 34 else 1))
all_data["feature_26_is_normal"] = all_data["feature_26"].apply(lambda x: 0 if x < 320 else (2 if x > 360 else 1))
all_data["feature_27_is_normal"] = all_data["feature_27"].apply(lambda x: 0 if x < 11.5 else (2 if x > 14.5 else 1))
all_data["feature_28_is_normal"] = all_data["feature_28"].apply(lambda x: 0 if x < 100 else (2 if x > 300 else 1))
all_data["feature_29_is_normal"] = all_data["feature_29"].apply(lambda x: 0 if x < 9 else (2 if x > 13 else 1))
all_data["feature_30_is_normal"] = all_data["feature_30"].apply(lambda x: 0 if x < 9 else (2 if x > 17 else 1))
all_data["feature_31_is_normal"] = all_data["feature_31"].apply(lambda x: 0 if x < 0.13 else (2 if x > 0.43 else 1))
all_data["feature_32_is_normal"] = all_data["feature_32"].apply(lambda x: 0 if x < 50 else (2 if x > 70 else 1))
all_data["feature_20_feature_32"] = round(all_data["feature_20"] * all_data['feature_32'],3) 
all_data["feature_33_is_normal"] = all_data["feature_33"].apply(lambda x: 0 if x < 20 else (2 if x > 40 else 1))
all_data["feature_20_feature_33"] = round(all_data["feature_20"] * all_data['feature_33'],3)
all_data["feature_34_is_normal"] = all_data["feature_34"].apply(lambda x: 0 if x < 3 else (2 if x > 8 else 1))
all_data["feature_20_feature_34"] = round(all_data["feature_20"] * all_data['feature_34'],3)
all_data["feature_35_is_normal"] = all_data["feature_35"].apply(lambda x: 0 if x < 0.5 else (2 if x > 5 else 1))
all_data["feature_20_feature_35"] = round(all_data["feature_20"] * all_data['feature_35'],3)
all_data["feature_36_is_normal"] = all_data["feature_36"].apply(lambda x: 0 if x < 0 else (2 if x > 1 else 1))
all_data["feature_20_feature_36"] = round(all_data["feature_20"] * all_data['feature_36'],3)

Wall time: 0 ns

In [132]:
gender_onehot_train = pd.get_dummies(all_data['gender'])
gender_onehot_train.rename(columns={0:'gender_0',1:'gender_1'},inplace=True)
all_data = pd.concat([all_data, gender_onehot_train],axis=1)

In [133]:
all_data.shape

(6606, 81)

In [103]:
all_data.head()

,age,blood_sugar,blood_sugar_log,date,feature_0,feature_1,feature_10,feature_11,feature_12,feature_13,...,feature_33_is_normal,feature_20_feature_33,feature_34_is_normal,feature_20_feature_34,feature_35_is_normal,feature_20_feature_35,feature_36_is_normal,feature_20_feature_36,gender_0,gender_1
0,41,6.06,0.529777,12/10/2017,24.96,23.10,1.37,2.65,5.87,77.25,...,1,182.628,1,34.710,1,25.098,1,3.204,0,1
1,41,5.39,0.651054,19/10/2017,24.57,36.25,0.93,2.63,5.26,87.12,...,1,280.755,1,44.370,1,35.955,1,6.120,0,1
2,46,5.59,0.610842,26/10/2017,20.82,15.23,1.64,2.01,4.77,78.19,...,2,185.380,1,35.420,1,14.720,1,3.680,0,1
3,22,4.30,0.974218,25/10/2017,14.99,10.59,1.43,5.04,4.23,61.46,...,2,435.240,1,62.712,1,43.056,1,4.680,1,0
4,74,5.97,0.544044,18/10/2017,23.72,22.59,1.81,4.28,6.11,66.66,...,2,329.000,1,49.700,1,14.700,1,7.000,1,0

In [134]:
train = all_data[:trains.shape[0]+vals.shape[0]]
tests = all_data[trains.shape[0] + vals.shape[0]:]

In [135]:
train.shape
tests.shape
train.columns

(5606, 81)

(1000, 81)

Index(['age', 'blood_sugar', 'blood_sugar_log', 'date', 'feature_0',
       'feature_1', 'feature_10', 'feature_11', 'feature_12', 'feature_13',
       'feature_14', 'feature_2', 'feature_20', 'feature_21', 'feature_22',
       'feature_23', 'feature_24', 'feature_25', 'feature_26', 'feature_27',
       'feature_28', 'feature_29', 'feature_3', 'feature_30', 'feature_31',
       'feature_32', 'feature_33', 'feature_34', 'feature_35', 'feature_36',
       'feature_4', 'feature_5', 'feature_6', 'feature_7', 'feature_8',
       'feature_9', 'gender', 'id', 'feature_0_is_normal',
       'feature_1_is_normal', 'feature_1_feature_0',
       'feature_1_feature_0_is_normal', 'feature_2_is_normal',
       'feature_3_is_normal', 'feature_4_is_normal', 'feature_5_is_normal',
       'feature_6_is_normal', 'feature_8_is_normal', 'feature_9_is_normal',
       'feature_10_is_normal', 'feature_10_gender_is_normal',
       'feature_11_is_normal', 'feature_10_feature_11', 'feature_12_is_normal',
       'feature_13_is_normal', 'feature_14_is_normal',
       'feature_14_gender_is_normal', 'feature_20_is_normal',
       'feature_21_is_normal', 'feature_22_is_normal', 'feature_23_is_normal',
       'feature_24_is_normal', 'feature_25_is_normal', 'feature_26_is_normal',
       'feature_27_is_normal', 'feature_28_is_normal', 'feature_29_is_normal',
       'feature_30_is_normal', 'feature_31_is_normal', 'feature_32_is_normal',
       'feature_20_feature_32', 'feature_33_is_normal',
       'feature_20_feature_33', 'feature_34_is_normal',
       'feature_20_feature_34', 'feature_35_is_normal',
       'feature_20_feature_35', 'feature_36_is_normal',
       'feature_20_feature_36', 'gender_0', 'gender_1'],
      dtype='object')

In [136]:
features_with_no_cate = [x for x in list(train.columns) if x not in ['id','date','blood_sugar_log',"gender"]]

In [137]:
train[features_with_no_cate].to_csv("../raw_data/fea_train.csv",index=False)
features_with_no_cate.remove("blood_sugar")
tests[features_with_no_cate].to_csv("../raw_data/fea_test.csv",index=False)

In [109]:
%time
model_lgb = lgb.LGBMRegressor(objective='regression',num_leaves=5,
                              learning_rate=0.05, n_estimators=720,
                              max_bin = 55, bagging_fraction = 0.8,
                              bagging_freq = 5, feature_fraction = 0.2319,
                              feature_fraction_seed=9, bagging_seed=9,
                              min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

score = rmsle_cv(model_lgb)
print("LGBM score: {:.4f} ({:.4f})\n" .format(score.mean(), score.std()))
model_lgb.fit(train, y_train)
lgb_train_pred = model_lgb.predict(train)
lgb_pred = model_lgb.predict(test.values)
print("train: ",rmsle(y_train, lgb_train_pred))
print("test: ",rmsle(y_test, lgb_pred))

['age',
 'feature_0',
 'feature_1',
 'feature_10',
 'feature_11',
 'feature_12',
 'feature_13',
 'feature_14',
 'feature_2',
 'feature_20',
 'feature_21',
 'feature_22',
 'feature_23',
 'feature_24',
 'feature_25',
 'feature_26',
 'feature_27',
 'feature_28',
 'feature_29',
 'feature_3',
 'feature_30',
 'feature_31',
 'feature_32',
 'feature_33',
 'feature_34',
 'feature_35',
 'feature_36',
 'feature_4',
 'feature_5',
 'feature_6',
 'feature_7',
 'feature_8',
 'feature_9',
 'feature_0_is_normal',
 'feature_1_is_normal',
 'feature_1_feature_0',
 'feature_1_feature_0_is_normal',
 'feature_2_is_normal',
 'feature_3_is_normal',
 'feature_4_is_normal',
 'feature_5_is_normal',
 'feature_6_is_normal',
 'feature_8_is_normal',
 'feature_9_is_normal',
 'feature_10_is_normal',
 'feature_10_gender_is_normal',
 'feature_11_is_normal',
 'feature_10_feature_11',
 'feature_12_is_normal',
 'feature_13_is_normal',
 'feature_14_is_normal',
 'feature_14_gender_is_normal',
 'feature_20_is_normal',
 'feature_21_is_normal',
 'feature_22_is_normal',
 'feature_23_is_normal',
 'feature_24_is_normal',
 'feature_25_is_normal',
 'feature_26_is_normal',
 'feature_27_is_normal',
 'feature_28_is_normal',
 'feature_29_is_normal',
 'feature_30_is_normal',
 'feature_31_is_normal',
 'feature_32_is_normal',
 'feature_20_feature_32',
 'feature_33_is_normal',
 'feature_20_feature_33',
 'feature_34_is_normal',
 'feature_20_feature_34',
 'feature_35_is_normal',
 'feature_20_feature_35',
 'feature_36_is_normal',
 'feature_20_feature_36',
 'gender_0',
 'gender_1']