<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#导入相关的包" data-toc-modified-id="导入相关的包-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>导入相关的包</a></span></li><li><span><a href="#导入相关数据" data-toc-modified-id="导入相关数据-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>导入相关数据</a></span></li><li><span><a href="#特征提取" data-toc-modified-id="特征提取-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>特征提取</a></span><ul class="toc-item"><li><span><a href="#是否在正常值范围内" data-toc-modified-id="是否在正常值范围内-3.1"><span class="toc-item-num">3.1&nbsp;&nbsp;</span>是否在正常值范围内</a></span></li><li><span><a href="#第二批特征" data-toc-modified-id="第二批特征-3.2"><span class="toc-item-num">3.2&nbsp;&nbsp;</span>第二批特征</a></span></li><li><span><a href="#第三次特征" data-toc-modified-id="第三次特征-3.3"><span class="toc-item-num">3.3&nbsp;&nbsp;</span>第三次特征</a></span></li></ul></li></ul></div>

# 导入相关的包

In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
%matplotlib inline

# 导入相关数据

In [21]:
%%time
trains = pd.read_csv('../clean_data/base_train.csv',encoding="gbk")
test = pd.read_csv('../clean_data/testB.csv',encoding='gbk')
vals = pd.read_csv('../clean_data/model_fill_train.csv',encoding='gbk')
all_data = pd.concat([trains, vals, test],axis=0,ignore_index=True)

Wall time: 228 ms

In [3]:
# raw_train = pd.read_csv("../raw_data/d_train.csv",encoding="gbk")
# raw_test = pd.read_csv("../raw_data/d_test_B_20180128.csv",encoding="gbk")
# raw_all_data = pd.concat([raw_train, raw_test],axis=0,ignore_index=True)

In [4]:
# raw_all_data.columns

In [5]:
# mer = raw_all_data[["id",'乙肝e抗体', '乙肝e抗原', '乙肝核心抗体', '乙肝表面抗体', '乙肝表面抗原',
# ]]

In [6]:
# data = all_data.merge(mer, how="left",on="id")

In [7]:
# data.sort_values(by= "id",inplace=True)

In [8]:
# train = data[:trains.shape[0]+vals.shape[0]]
# tests = data[trains.shape[0] + vals.shape[0]:]
# train.to_csv("../raw_data/fea_train_raw.csv",index=False)
# tests.to_csv("../raw_data/fea_test_B_1.csv",index=False)

In [9]:
all_data.head()

,age,blood_sugar,date,feature_0,feature_1,feature_10,feature_11,feature_12,feature_13,feature_14,...,feature_35,feature_36,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,gender,id
0,41,6.06,12/10/2017,24.96,23.10,1.37,2.65,5.87,77.25,349.39,...,4.7,0.6,76.88,49.60,27.28,1.82,1.31,4.43,1,1
1,41,5.39,19/10/2017,24.57,36.25,0.93,2.63,5.26,87.12,486.78,...,4.7,0.8,79.43,47.76,31.67,1.51,2.81,4.06,1,2
2,46,5.59,26/10/2017,20.82,15.23,1.64,2.01,4.77,78.19,452.07,...,3.2,0.8,86.23,48.00,38.23,1.26,0.99,4.13,1,3
3,22,4.30,25/10/2017,14.99,10.59,1.43,5.04,4.23,61.46,368.85,...,4.6,0.5,70.98,44.02,26.96,1.63,1.06,6.89,0,4
4,74,5.97,18/10/2017,23.72,22.59,1.81,4.28,6.11,66.66,383.87,...,2.1,1.0,76.46,45.85,30.61,1.50,2.45,6.65,0,6

In [10]:
trains.shape
test.shape
vals.shape
all_data.shape

(7636, 37)

In [11]:
all_data["blood_sugar"].describe()
test["age"].describe()

count    1000.000000
mean       45.769000
std        12.781275
min        19.000000
25%        36.000000
50%        45.000000
75%        55.000000
max        86.000000
Name: age, dtype: float64

# 特征提取

## 是否在正常值范围内

In [12]:
all_data.columns
all_data

,age,blood_sugar,date,feature_0,feature_1,feature_10,feature_11,feature_12,feature_13,feature_14,...,feature_35,feature_36,feature_4,feature_5,feature_6,feature_7,feature_8,feature_9,gender,id
0,41,6.06,12/10/2017,24.960,23.100,1.370,2.650,5.870,77.250,349.390,...,4.7,0.6,76.880,49.600,27.280,1.820,1.310,4.430,1,1
1,41,5.39,19/10/2017,24.570,36.250,0.930,2.630,5.260,87.120,486.780,...,4.7,0.8,79.430,47.760,31.670,1.510,2.810,4.060,1,2
2,46,5.59,26/10/2017,20.820,15.230,1.640,2.010,4.770,78.190,452.070,...,3.2,0.8,86.230,48.000,38.230,1.260,0.990,4.130,1,3
3,22,4.30,25/10/2017,14.990,10.590,1.430,5.040,4.230,61.460,368.850,...,4.6,0.5,70.980,44.020,26.960,1.630,1.060,6.890,0,4
4,74,5.97,18/10/2017,23.720,22.590,1.810,4.280,6.110,66.660,383.870,...,2.1,1.0,76.460,45.850,30.610,1.500,2.450,6.650,0,6
5,31,5.11,21/09/2017,24.970,25.530,1.330,3.820,6.140,95.980,446.100,...,3.1,0.7,80.820,46.400,34.420,1.350,1.510,5.600,1,7
6,55,5.94,21/09/2017,37.320,40.030,1.280,4.200,6.310,92.160,344.730,...,2.8,0.9,74.170,41.630,32.540,1.280,1.320,5.920,1,8
7,39,5.66,16/10/2017,21.700,39.170,1.510,3.600,4.980,78.570,353.310,...,3.3,0.4,76.120,49.310,26.810,1.840,2.070,5.500,1,9
8,35,5.48,10/10/2017,18.890,15.790,1.550,2.020,6.610,86.880,266.520,...,1.0,0.7,75.940,46.640,29.300,1.590,1.250,3.980,0,10
9,47,4.44,13/10/2017,27.330,35.760,0.900,2.840,5.600,66.490,333.600,...,1.3,0.9,75.840,43.710,32.130,1.360,1.960,4.320,1,11
10,50,5.48,10/10/2017,22.890,28.460,1.140,2.650,4.690,74.530,493.070,...,1.2,0.4,73.800,48.320,25.480,1.900,3.320,4.470,1,12
11,48,5.32,19/10/2017,30.110,34.700,1.430,1.940,4.390,67.540,264.320,...,4.2,1.3,77.860,43.050,34.810,1.240,1.210,3.690,0,13
12,36,5.08,11/10/2017,16.820,11.800,1.930,0.560,3.470,73.260,345.480,...,0.6,0.3,76.840,47.560,29.280,1.620,0.270,2.850,0,14
13,37,4.63,27/09/2017,24.580,24.640,1.210,3.550,3.460,65.990,383.200,...,1.5,0.8,92.310,46.980,45.330,1.040,1.220,5.200,0,15
14,43,4.92,28/09/2017,20.070,14.810,1.580,3.520,5.670,62.260,300.920,...,1.1,0.5,74.430,44.490,29.940,1.490,1.520,5.510,0,16
15,77,7.08,24/10/2017,18.490,17.290,1.020,2.490,10.680,134.630,437.370,...,1.9,0.4,76.020,42.390,33.630,1.260,4.590,4.050,1,17
16,42,4.66,16/10/2017,24.710,30.260,1.110,4.070,6.770,90.660,485.170,...,1.0,0.2,81.870,43.850,38.020,1.150,3.870,5.830,1,18
17,39,6.58,30/10/2017,31.440,43.970,1.110,3.400,4.750,107.330,565.310,...,3.5,0.8,79.740,46.490,33.250,1.400,1.330,4.550,1,19
18,38,4.29,28/09/2017,23.580,31.190,1.200,4.290,3.070,94.160,468.950,...,1.3,0.4,81.500,51.160,30.340,1.690,2.630,5.930,1,20
19,30,4.55,29/09/2017,33.250,67.190,1.180,4.020,3.790,103.150,493.380,...,2.0,0.6,82.800,49.320,33.480,1.470,3.440,5.500,1,21
20,51,5.16,26/10/2017,26.530,20.440,1.360,2.810,4.250,98.690,398.200,...,2.4,0.3,75.700,48.680,27.020,1.800,1.870,4.480,1,22
21,38,5.13,19/10/2017,24.130,34.020,1.730,2.710,3.560,65.550,236.150,...,4.3,0.7,76.120,44.870,31.250,1.440,1.420,4.780,0,23
22,33,4.37,30/09/2017,15.770,11.430,1.220,1.970,5.930,65.040,254.750,...,1.1,0.4,83.110,47.370,35.740,1.330,0.940,3.490,0,24
23,28,5.17,20/10/2017,20.240,12.550,1.920,2.450,4.270,71.370,241.980,...,0.8,0.6,76.970,47.890,29.080,1.650,0.600,4.880,0,25
24,34,4.64,30/10/2017,20.890,16.160,1.470,4.370,4.360,68.110,263.350,...,0.3,0.6,77.070,43.720,33.350,1.310,1.400,5.930,0,26
25,34,5.82,30/10/2017,32.030,52.740,1.680,4.130,6.200,80.230,446.160,...,1.1,0.6,79.110,50.400,28.710,1.760,1.180,5.930,1,27
26,38,6.29,31/10/2017,34.620,54.430,1.120,3.920,4.000,88.320,336.440,...,1.9,0.8,78.470,49.260,29.210,1.690,2.460,5.370,1,28
27,60,5.10,24/10/2017,28.360,32.300,1.530,2.690,8.250,78.720,322.390,...,1.7,0.8,71.380,43.210,28.170,1.530,0.920,4.590,1,29
28,55,5.41,17/10/2017,29.600,34.070,1.250,3.580,5.330,88.480,389.350,...,2.6,1.2,82.330,45.490,36.840,1.230,1.620,5.280,1,30
29,56,5.48,17/10/2017,22.680,16.930,2.070,2.850,3.660,68.160,245.800,...,1.8,0.4,73.750,47.420,26.330,1.800,0.690,5.410,1,31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7606,28,NaN,31/10/2017,21.470,22.950,1.365,3.171,3.860,87.620,361.940,...,1.2,0.4,77.190,48.850,28.340,1.720,1.609,4.832,1,7780
7607,76,NaN,31/10/2017,27.250,13.940,1.320,2.440,6.870,82.010,402.100,...,1.1,0.8,74.640,39.260,35.380,1.110,1.530,3.940,0,7781
7608,40,NaN,31/10/2017,18.500,11.390,1.550,3.250,4.420,77.200,373.390,...,1.3,0.7,73.680,46.000,27.680,1.660,0.810,5.130,1,7782
7609,44,NaN,31/10/2017,43.710,63.890,1.010,3.320,4.370,79.130,400.170,...,2.6,0.5,73.450,46.570,26.880,1.730,2.260,4.520,1,7783
7610,40,NaN,31/10/2017,22.180,16.520,1.570,3.410,4.662,71.005,329.906,...,1.8,0.5,78.770,45.800,32.970,1.390,1.470,5.110,0,7784
7611,31,NaN,31/10/2017,15.810,7.040,1.620,2.600,4.780,57.900,291.770,...,3.1,0.6,76.670,44.280,32.390,1.370,0.480,4.380,0,7785
7612,40,NaN,31/10/2017,20.950,15.270,2.000,2.890,4.560,65.190,171.240,...,0.5,0.8,74.870,45.930,28.940,1.590,0.970,5.070,0,7786
7613,32,NaN,31/10/2017,21.170,13.740,1.910,3.130,3.320,57.480,231.250,...,2.8,1.0,74.560,44.420,30.140,1.470,0.850,5.170,0,7787
7614,58,NaN,31/10/2017,25.831,22.777,1.479,3.319,5.019,73.038,319.896,...,2.1,0.7,76.079,45.136,30.799,1.506,1.820,5.257,0,7788
7615,54,NaN,31/10/2017,32.510,30.460,1.430,4.860,3.070,60.980,260.800,...,2.9,1.1,76.440,46.350,30.090,1.540,1.790,6.470,0,7789
7616,63,NaN,31/10/2017,22.750,21.580,1.620,2.250,4.850,73.990,350.620,...,4.6,1.3,74.050,43.470,30.580,1.420,2.180,4.680,1,7790
7617,39,NaN,31/10/2017,19.560,20.970,1.200,3.440,4.680,76.560,411.880,...,2.4,0.4,74.510,46.490,28.020,1.660,1.110,5.300,1,7791
7618,48,NaN,31/10/2017,29.140,28.510,1.710,4.570,5.570,75.920,370.410,...,0.9,0.4,75.450,48.540,26.910,1.800,2.260,6.590,1,7792
7619,53,NaN,31/10/2017,22.090,19.300,1.220,2.770,4.750,66.910,219.740,...,2.2,1.1,73.680,43.890,29.790,1.470,0.810,4.190,0,7794
7620,65,NaN,31/10/2017,30.960,32.090,1.660,4.510,5.180,66.590,344.820,...,1.1,0.5,74.210,42.280,31.930,1.320,1.250,6.310,0,7795
7621,56,NaN,31/10/2017,29.082,27.030,1.413,3.383,5.227,80.361,351.395,...,0.5,0.5,75.817,45.656,30.407,1.525,1.715,5.329,1,7796
7622,69,NaN,31/10/2017,17.120,8.940,1.140,2.270,4.190,63.790,147.680,...,0.6,0.4,74.650,44.060,30.590,1.440,1.770,3.580,0,7797
7623,41,NaN,31/10/2017,18.880,8.260,1.450,2.340,3.280,75.570,217.790,...,0.5,0.3,74.780,45.520,29.260,1.560,0.650,3.940,0,7798
7624,23,NaN,31/10/2017,17.630,7.770,1.700,3.590,4.640,64.490,197.370,...,2.9,0.9,72.510,36.850,35.660,1.030,0.920,5.510,0,7800
7625,65,NaN,31/10/2017,19.140,16.080,1.430,3.500,6.830,101.340,383.490,...,1.7,0.8,72.350,41.210,31.140,1.320,1.010,5.190,1,7801
7626,63,NaN,31/10/2017,27.340,21.020,2.030,5.120,3.750,68.010,284.780,...,0.3,0.8,84.240,49.960,34.280,1.460,1.300,8.140,0,7802
7627,55,NaN,31/10/2017,23.330,13.940,1.920,5.600,3.250,64.610,332.080,...,0.8,0.5,77.840,46.690,31.150,1.500,4.770,8.350,0,7803
7628,80,NaN,31/10/2017,17.220,10.450,1.110,2.990,5.880,97.590,404.190,...,1.6,0.5,77.280,39.580,37.700,1.050,1.850,4.830,1,7804
7629,43,NaN,31/10/2017,31.693,30.525,1.220,2.680,5.054,80.958,361.254,...,3.8,1.1,76.462,45.744,30.687,1.516,1.140,4.230,1,7805
7630,57,NaN,31/10/2017,17.930,12.440,1.330,4.510,6.180,80.140,352.960,...,1.2,1.5,76.230,44.280,31.950,1.390,1.880,6.330,0,7806
7631,61,NaN,31/10/2017,20.850,16.880,1.850,3.760,9.740,67.280,210.340,...,2.4,1.0,74.040,43.000,31.040,1.390,1.010,5.890,0,7807
7632,64,NaN,31/10/2017,18.350,15.200,1.280,3.660,6.210,59.510,310.130,...,1.5,0.5,68.990,42.200,26.790,1.580,0.930,5.170,0,7808
7633,64,NaN,31/10/2017,31.290,21.960,1.250,2.160,6.140,75.720,446.710,...,6.3,0.9,71.430,45.310,26.120,1.730,2.690,3.950,1,7809
7634,52,NaN,31/10/2017,15.840,9.070,1.050,2.490,3.930,62.620,236.070,...,0.8,0.3,73.480,43.660,29.820,1.460,1.100,3.670,0,7810
7635,55,NaN,31/10/2017,26.050,17.260,1.350,4.660,5.140,72.410,258.130,...,2.3,0.8,77.200,46.130,31.070,1.480,1.770,6.560,0,7811

In [13]:
%%time
all_data["feature_0_is_normal"] = all_data["feature_0"].apply(lambda x: 0 if x < 10 else (2 if x > 40 else 1))
all_data["feature_1_is_normal"] = all_data["feature_1"].apply(lambda x: 0 if x < 10 else (2 if x > 40 else 1))
all_data["feature_1_feature_0"] = round(all_data["feature_0"] / all_data['feature_1'],3)
all_data["feature_1_feature_0_is_normal"] = all_data["feature_1_feature_0"].apply(lambda x: 0 if x > 1 else 1)
all_data["feature_2_is_normal"] = all_data["feature_2"].apply(lambda x: 0 if x < 40 else (2 if x > 150 else 1))
all_data["feature_3_is_normal"] = all_data[["feature_3","gender"]].apply(lambda x: 
                                       (0 if x[0] < 11 else(2 if x[0] > 50 else 1)) if x[1] == 1 else (3 if x[0] < 7 else(5 if x[0] > 32 else 4)), 
                                       axis=1)
all_data["feature_4_is_normal"] = all_data["feature_4"].apply(lambda x: 0 if x < 60 else (2 if x > 80 else 1))
all_data["feature_5_is_normal"] = all_data["feature_5"].apply(lambda x: 0 if x < 40 else (2 if x > 55 else 1))
all_data["feature_6_is_normal"] = all_data["feature_6"].apply(lambda x: 0 if x < 20 else (2 if x > 30 else 1))
all_data["feature_8_is_normal"] = all_data["feature_8"].apply(lambda x: 0 if x < 0.42 else (2 if x > 1.82 else 1))
all_data["feature_9_is_normal"] = all_data["feature_9"].apply(lambda x: 0 if x < 2.9 else (2 if x > 6 else 1))
all_data["feature_10_is_normal"] = all_data["feature_10"].apply(lambda x: 0 if x < 1.16 else (2 if x > 1.55 else 1))
all_data["feature_10_gender_is_normal"] = all_data[["feature_10","gender"]].apply(lambda x:
                                       (0 if x[0] < 1.1 else 1) if x[1] == 1 else (2 if x[0] < 1.2 else 3),
                                       axis=1)
all_data["feature_11_is_normal"] = all_data["feature_11"].apply(lambda x: 0 if x < 2.84 else (2 if x > 3.12 else 1))
all_data["feature_10_feature_11"] = round(all_data["feature_11"] / all_data['feature_10'],3)
all_data["feature_12_is_normal"] = all_data["feature_12"].apply(lambda x: 0 if x < 1.7 else (2 if x > 8.3 else 1))
all_data["feature_13_is_normal"] = all_data[["feature_13","gender"]].apply(lambda x:
                                       (0 if x[0] < 53 else(2 if x[0] > 106 else 1)) if x[1] == 1 else (3 if x[0] < 44 else(5 if x[0] > 97 else 4)),
                                       axis=1)
all_data["feature_14_is_normal"] = all_data[["feature_14","gender"]].apply(lambda x:
                                       (0 if x[0] < 150 else(2 if x[0] > 416 else 1)) if x[1] == 1 else (3 if x[0] < 89 else(5 if x[0] > 357 else 4)),
                                       axis=1)
all_data["feature_14_gender_is_normal"] = all_data[["feature_14","gender"]].apply(lambda x:
                                       (0 if x[0] > 420 else 1) if x[1] == 1 else (2 if x[0] > 350 else 3),
                                       axis=1)
all_data["feature_20_is_normal"] = all_data["feature_20"].apply(lambda x: 0 if x < 4 else (2 if x > 10 else 1))
all_data["feature_21_is_normal"] = all_data[["feature_21","gender"]].apply(lambda x:
                                       (0 if x[0] < 4.0 else(2 if x[0] > 5.5 else 1)) if x[1] == 1 else (3 if x[0] < 3.5 else(5 if x[0] > 5.0 else 4)),
                                       axis=1)
all_data["feature_22_is_normal"] = all_data[["feature_22","gender"]].apply(lambda x:
                                       (0 if x[0] < 120 else(2 if x[0] > 160 else 1)) if x[1] == 1 else (3 if x[0] < 110 else(5 if x[0] > 150 else 4)),
                                       axis=1)
all_data["feature_23_is_normal"] = all_data[["feature_23","gender"]].apply(lambda x:
                                       (0 if x[0] < 0.4 else(2 if x[0] > 0.5 else 1)) if x[1] == 1 else (3 if x[0] < 0.37 else(5 if x[0] > 0.48 else 4)),
                                       axis=1)
all_data["feature_24_is_normal"] = all_data["feature_24"].apply(lambda x: 0 if x < 80 else (2 if x > 100 else 1))
all_data["feature_25_is_normal"] = all_data["feature_25"].apply(lambda x: 0 if x < 27 else (2 if x > 34 else 1))
all_data["feature_26_is_normal"] = all_data["feature_26"].apply(lambda x: 0 if x < 320 else (2 if x > 360 else 1))
all_data["feature_27_is_normal"] = all_data["feature_27"].apply(lambda x: 0 if x < 11.5 else (2 if x > 14.5 else 1))
all_data["feature_28_is_normal"] = all_data["feature_28"].apply(lambda x: 0 if x < 100 else (2 if x > 300 else 1))
all_data["feature_29_is_normal"] = all_data["feature_29"].apply(lambda x: 0 if x < 9 else (2 if x > 13 else 1))
all_data["feature_30_is_normal"] = all_data["feature_30"].apply(lambda x: 0 if x < 9 else (2 if x > 17 else 1))
all_data["feature_31_is_normal"] = all_data["feature_31"].apply(lambda x: 0 if x < 0.11 else (2 if x > 0.23 else 1))
all_data["feature_32_is_normal"] = all_data["feature_32"].apply(lambda x: 0 if x < 50 else (2 if x > 70 else 1))
all_data["feature_20_feature_32"] = round(all_data["feature_20"] * all_data['feature_32'],3) 
all_data["feature_33_is_normal"] = all_data["feature_33"].apply(lambda x: 0 if x < 20 else (2 if x > 40 else 1))
all_data["feature_20_feature_33"] = round(all_data["feature_20"] * all_data['feature_33'],3)
all_data["feature_34_is_normal"] = all_data["feature_34"].apply(lambda x: 0 if x < 3 else (2 if x > 8 else 1))
all_data["feature_20_feature_34"] = round(all_data["feature_20"] * all_data['feature_34'],3)
all_data["feature_35_is_normal"] = all_data["feature_35"].apply(lambda x: 0 if x < 0.5 else (2 if x > 5 else 1))
all_data["feature_20_feature_35"] = round(all_data["feature_20"] * all_data['feature_35'],3)
all_data["feature_36_is_normal"] = all_data["feature_36"].apply(lambda x: 0 if x < 0 else (2 if x > 1 else 1))
all_data["feature_20_feature_36"] = round(all_data["feature_20"] * all_data['feature_36'],3)

Wall time: 10.6 s

In [14]:
gender_onehot_train = pd.get_dummies(all_data['gender'])
gender_onehot_train.rename(columns={0:'gender_0',1:'gender_1'},inplace=True)
all_data = pd.concat([all_data, gender_onehot_train],axis=1)

In [15]:
all_data.shape

(7636, 80)

In [16]:
all_data.head()

,age,blood_sugar,date,feature_0,feature_1,feature_10,feature_11,feature_12,feature_13,feature_14,...,feature_33_is_normal,feature_20_feature_33,feature_34_is_normal,feature_20_feature_34,feature_35_is_normal,feature_20_feature_35,feature_36_is_normal,feature_20_feature_36,gender_0,gender_1
0,41,6.06,12/10/2017,24.96,23.10,1.37,2.65,5.87,77.25,349.39,...,1,182.628,1,34.710,1,25.098,1,3.204,0,1
1,41,5.39,19/10/2017,24.57,36.25,0.93,2.63,5.26,87.12,486.78,...,1,280.755,1,44.370,1,35.955,1,6.120,0,1
2,46,5.59,26/10/2017,20.82,15.23,1.64,2.01,4.77,78.19,452.07,...,2,185.380,1,35.420,1,14.720,1,3.680,0,1
3,22,4.30,25/10/2017,14.99,10.59,1.43,5.04,4.23,61.46,368.85,...,2,435.240,1,62.712,1,43.056,1,4.680,1,0
4,74,5.97,18/10/2017,23.72,22.59,1.81,4.28,6.11,66.66,383.87,...,2,329.000,1,49.700,1,14.700,1,7.000,1,0

In [17]:
train = all_data[:trains.shape[0]+vals.shape[0]]
tests = all_data[trains.shape[0] + vals.shape[0]:]

In [18]:
train.shape
tests.shape
train.columns

Index(['age', 'blood_sugar', 'date', 'feature_0', 'feature_1', 'feature_10',
       'feature_11', 'feature_12', 'feature_13', 'feature_14', 'feature_2',
       'feature_20', 'feature_21', 'feature_22', 'feature_23', 'feature_24',
       'feature_25', 'feature_26', 'feature_27', 'feature_28', 'feature_29',
       'feature_3', 'feature_30', 'feature_31', 'feature_32', 'feature_33',
       'feature_34', 'feature_35', 'feature_36', 'feature_4', 'feature_5',
       'feature_6', 'feature_7', 'feature_8', 'feature_9', 'gender', 'id',
       'feature_0_is_normal', 'feature_1_is_normal', 'feature_1_feature_0',
       'feature_1_feature_0_is_normal', 'feature_2_is_normal',
       'feature_3_is_normal', 'feature_4_is_normal', 'feature_5_is_normal',
       'feature_6_is_normal', 'feature_8_is_normal', 'feature_9_is_normal',
       'feature_10_is_normal', 'feature_10_gender_is_normal',
       'feature_11_is_normal', 'feature_10_feature_11', 'feature_12_is_normal',
       'feature_13_is_normal', 'feature_14_is_normal',
       'feature_14_gender_is_normal', 'feature_20_is_normal',
       'feature_21_is_normal', 'feature_22_is_normal', 'feature_23_is_normal',
       'feature_24_is_normal', 'feature_25_is_normal', 'feature_26_is_normal',
       'feature_27_is_normal', 'feature_28_is_normal', 'feature_29_is_normal',
       'feature_30_is_normal', 'feature_31_is_normal', 'feature_32_is_normal',
       'feature_20_feature_32', 'feature_33_is_normal',
       'feature_20_feature_33', 'feature_34_is_normal',
       'feature_20_feature_34', 'feature_35_is_normal',
       'feature_20_feature_35', 'feature_36_is_normal',
       'feature_20_feature_36', 'gender_0', 'gender_1'],
      dtype='object')

In [19]:
# features_with_no_cate = [x for x in list(train.columns) if x not in ['id','date','blood_sugar_log',"gender"]]
cate_fea =  [ 'feature_0_is_normal',
       'feature_1_is_normal',
       'feature_1_feature_0_is_normal', 'feature_2_is_normal',
       'feature_3_is_normal', 'feature_4_is_normal', 'feature_5_is_normal',
       'feature_6_is_normal', 'feature_8_is_normal', 'feature_9_is_normal',
       'feature_10_is_normal', 'feature_10_gender_is_normal',
       'feature_11_is_normal', 'feature_12_is_normal',
       'feature_13_is_normal', 'feature_14_is_normal',
       'feature_14_gender_is_normal', 'feature_20_is_normal',
       'feature_21_is_normal', 'feature_22_is_normal', 'feature_23_is_normal',
       'feature_24_is_normal', 'feature_25_is_normal', 'feature_26_is_normal',
       'feature_27_is_normal', 'feature_28_is_normal', 'feature_29_is_normal',
       'feature_30_is_normal', 'feature_31_is_normal', 'feature_32_is_normal',"feature_1_feature_0",'feature_10_feature_11',
       'feature_20_feature_32', 'feature_33_is_normal',
       'feature_20_feature_33', 'feature_34_is_normal',
       'feature_20_feature_34', 'feature_35_is_normal',
       'feature_20_feature_35', 'feature_36_is_normal',
       'feature_20_feature_36',"id","gender_0","gender_1"]

In [20]:
train[cate_fea].to_csv("../raw_data/fea_train.csv",index=False)
# features_with_no_cate.remove("blood_sugar")
tests[cate_fea].to_csv("../raw_data/fea_test_B.csv",index=False)

In [138]:
%time
# model_lgb = lgb.LGBMRegressor(objective='regression',num_leaves=5,
#                               learning_rate=0.05, n_estimators=720,
#                               max_bin = 55, bagging_fraction = 0.8,
#                               bagging_freq = 5, feature_fraction = 0.2319,
#                               feature_fraction_seed=9, bagging_seed=9,
#                               min_data_in_leaf =6, min_sum_hessian_in_leaf = 11)

# score = rmsle_cv(model_lgb)
# print("LGBM score: {:.4f} ({:.4f})\n" .format(score.mean(), score.std()))
# model_lgb.fit(train, y_train)
# lgb_train_pred = model_lgb.predict(train)
# lgb_pred = model_lgb.predict(test.values)
# print("train: ",rmsle(y_train, lgb_train_pred))
# print("test: ",rmsle(y_test, lgb_pred))

Wall time: 0 ns

NameError: name 'lgb' is not defined

## 第二批特征

In [23]:
%%time
all_data["feature_28_feature_31"] = all_data["feature_28"] * all_data["feature_31"]
all_data["ATSs"] = all_data["feature_0"] * 0.8
all_data["ATSm"] = all_data["feature_0"] * 0.2
all_data["feature_0_feature_1"] = all_data["feature_0"] + all_data["feature_1"]
all_data["feature_4_less_60"] = all_data["feature_4"].apply(lambda x: 1 if x < 60 else 0)
all_data["feature_5_less_25"] = all_data["feature_5"].apply(lambda x: 1 if x < 25 else 0)
all_data["feature_4_feature_5"] = all_data["feature_4"] + all_data["feature_5"]
all_data["feature_4_feature_6"] = all_data["feature_4"] + all_data["feature_6"]
all_data["feature_32_feature_33"] = round(all_data["feature_32"] / all_data["feature_33"],3)
all_data["feature_12_feature_13"] = round(all_data["feature_12"] / all_data["feature_13"],3)
all_data["feature_8_feature_9"] = all_data["feature_8"] + all_data["feature_9"]
# all_data["feature_9_95"] = all_data["feature_9"] * 0.95
all_data["feature_9_gt_572"] = all_data["feature_9"].apply(lambda x: 1 if x > 5.72 else 0)
all_data["feature_8_gt_17"] = all_data["feature_8"].apply(lambda x: 1 if x > 1.72 else 0)
all_data["feature_10_lt_129"] = all_data["feature_10"].apply(lambda x: 1 if x < 1.29 else 0)
all_data["feature_11_gt_312"] = all_data["feature_11"].apply(lambda x: 1 if x > 3.12 else 0)
# all_data["feature_28_add_29"] = all_data["feature_28"] + all_data["feature_29"]
# all_data["feature_28_mul_29"] = all_data["feature_28"] * all_data["feature_29"]
all_data["feature_28_feature_31"] = round(all_data["feature_28"] / all_data["feature_31"],3)

Wall time: 80 ms

In [24]:
all_data = all_data[["id",'feature_28_feature_31', 'ATSs', 'ATSm',
       'feature_0_feature_1', 'feature_4_less_60', 'feature_5_less_25',
       'feature_4_feature_5', 'feature_4_feature_6','feature_32_feature_33','feature_12_feature_13',
        'feature_8_feature_9','feature_9_gt_572','feature_8_gt_17','feature_10_lt_129',
        'feature_11_gt_312','feature_28_feature_31']]

In [25]:
train = all_data[:trains.shape[0]+vals.shape[0]]
tests = all_data[trains.shape[0] + vals.shape[0]:]
train.to_csv("../raw_data/fea_train_1.csv",index=False)
tests.to_csv("../raw_data/fea_test_B_1.csv",index=False)

In [22]:
train.shape

(5622, 17)


## 第三次特征

In [ ]:
all_data["df_feature_0_1_2_3"] = all_data["feature_0"] + all_data["feature_1"] + all_data["feature_2"] + all_data["feature_3"]
all_data["df_feature_12_13_14"] = all_data["feature_12"] + all_data["feature_13"] + all_data["feature_14"]
all_data["df_feature_21_24"] = all_data["feature_21"] * all_data["feature_24"]
all_data["df_feature_21_25"] = all_data["feature_21"] * all_data["feature_25"]
all_data["df_feature_21_26"] = all_data["feature_21"] * all_data["feature_26"]
all_data["df_feature_22_21_26"] = all_data["feature_22"] / all_data["df_feature_21_26"]