<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc" style="margin-top: 1em;"><ul class="toc-item"><li><span><a href="#导入相关的包" data-toc-modified-id="导入相关的包-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>导入相关的包</a></span></li><li><span><a href="#导入相关数据" data-toc-modified-id="导入相关数据-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>导入相关数据</a></span></li></ul></div>

# 导入相关的包

In [9]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")

In [13]:
pred1 = pd.read_csv("../submission/biorad_sub_lgb_c_8179.csv",names=["pred"])
pred2 = pd.read_csv("../raw_data/d_answer_a_20180128.csv",names=["pred"])
res = pd.DataFrame()
res["pred1"] = pred1.pred.values
res["pred2"] = pred2.pred.values
res["pred"] = res["pred2"] - res["pred1"]

In [15]:
res.to_csv("../bi.csv",index=False)

In [6]:
pred1 = pd.read_csv("../submission/lgb.csv",names=["pred"])
pred2 = pd.read_csv("../submission/df_lgb.csv",names=["pred"])
res = pd.DataFrame()
res["pred1"] = pred1.pred.values
res["pred2"] = pred2.pred.values
res["pred"] = (res["pred1"] + res["pred2"]) / 2
res["pred"] = round(res["pred"],3)
res["pred"].to_csv("../submission/biorad.csv",index=False, header=False)

In [8]:
res.sort_values(by="pred",ascending=False)

         pred1     pred2   pred
270  10.116279  7.662205  8.889
383   8.084540  8.140143  8.112
308   8.197653  8.023144  8.110
957   8.284799  7.388776  7.837
138   8.141126  7.181474  7.661
525   7.846282  7.468932  7.658
400   7.712281  7.524511  7.618
324   7.430113  7.731997  7.581
939   7.031431  7.992780  7.512
839   8.012873  6.985664  7.499
885   7.827012  7.109564  7.468
678   7.873565  6.882365  7.378
457   7.281823  7.424681  7.353
146   7.207360  7.445046  7.326
200   7.006564  7.493919  7.250
992   6.792130  7.482024  7.137
931   7.162302  7.084336  7.123
952   7.040703  7.172394  7.107
203   6.901069  7.295024  7.098
444   6.924981  7.197314  7.061
112   6.615004  7.454457  7.035
932   7.134255  6.931347  7.033
258   7.007972  7.008153  7.008
918   6.989035  6.942401  6.966
878   7.300667  6.601167  6.951
776   6.955911  6.931874  6.944
835   7.124891  6.688700  6.907
440   7.726691  5.943195  6.835
877   6.900310  6.733082  6.817
895   7.124872  6.460262  6.793
..         ...       ...    ...
988   4.979086  4.856404  4.918
311   4.878689  4.958029  4.918
640   4.861842  4.974569  4.918
246   4.914156  4.915318  4.915
433   4.892823  4.933660  4.913
859   4.916777  4.906225  4.912
950   4.905204  4.908792  4.907
319   4.906873  4.904154  4.906
924   4.905691  4.904600  4.905
119   4.892189  4.909688  4.901
567   4.898811  4.902969  4.901
891   4.870587  4.925100  4.898
32    4.893697  4.900730  4.897
242   4.903048  4.883006  4.893
18    4.860183  4.914960  4.888
775   4.843287  4.931623  4.887
661   4.848455  4.916351  4.882
854   4.841156  4.915276  4.878
518   4.917348  4.839552  4.878
739   4.815619  4.935165  4.875
346   4.836064  4.906122  4.871
337   4.832317  4.894479  4.863
427   4.827120  4.898957  4.863
254   4.856335  4.864468  4.860
975   4.846867  4.870968  4.859
342   4.795655  4.910935  4.853
837   4.835808  4.868121  4.852
514   4.769228  4.875377  4.822
511   4.807780  4.826879  4.817
95    4.775588  4.826955  4.801

[1000 rows x 3 columns]

# 导入相关数据

In [10]:
old = pd.read_csv("../regression/sub_B.csv")
result_pred = pd.read_csv("../submission/sub_lgb_B_28_h.csv",names=["pred"])
result_pred["id"] = old["id"]
print("begin process gt10..")

begin process gt10..

In [11]:
result_pred.head()

       pred    id
0  5.549301  6769
1  5.672529  6770
2  5.713864  6771
3  5.012899  6772
4  6.320231  6773

In [12]:
old.head()

     id      pred
0  6769  5.549301
1  6770  5.672529
2  6771  5.713864
3  6772  5.012899
4  6773  6.320231

In [11]:
gt10_prob = pd.read_csv("../classification/result/gt10.csv")
print(gt10_prob.index)
gt10_prob.sort_values(by='gt10_prob',inplace=True)
gt10_prob = gt10_prob.tail(9)
result_pred = pd.merge(result_pred,gt10_prob,on='id',how='left')
result_pred.fillna(-999,inplace=True)
result_pred_sou = result_pred[result_pred.gt10_prob==-999]
result_pred_gt = result_pred[result_pred.gt10_prob != -999]
result_pred = result_pred_sou[['id','pred']]
result_pred_gt["pred"] = result_pred_gt["pred"] * 1.2
result_pred_gt = result_pred_gt[["id","pred"]]

RangeIndex(start=0, stop=1000, step=1)

In [12]:
gt10_prob

       id  gt10_prob
776  7578   0.515297
432  7228   0.546891
878  7685   0.546935
138  6924   0.566180
839  7644   0.693358
874  7681   0.711185
308  7097   0.824322
270  7057   0.857545
383  7175   0.876149

In [14]:
result_pred_gt

       id       pred
138  6924   9.488322
270  7057  12.191172
308  7097   9.961186
444  7240   8.346306
769  7570   7.635586
798  7603   7.845842
835  7640   8.491344
839  7644   9.163336
874  7681   8.262943

In [41]:
lt45_prob = pd.read_csv('../classification/result/lt45.csv')
lt45_prob.sort_values(by='lt45_prob',inplace=True)
lt45 = lt45_prob.tail(5)
result_pred = pd.merge(result_pred,lt45,on='id',how='left')
result_pred.fillna(-999,inplace=True)
result_pred_sor = result_pred[result_pred.lt45_prob==-999]
result_pred_lt = result_pred[result_pred.lt45_prob !=-999]
result_pred = result_pred_sor[['id','pred']]
result_pred_lt["pred"] = result_pred_lt["pred"] * 0.9
result_pred_lt = result_pred_lt[["id","pred"]]

In [42]:
lt45_prob

       id  lt45_prob
736  6494   0.000030
379  6125   0.000035
859  6622   0.000040
205  5942   0.000045
423  6170   0.000057
283  6021   0.000069
515  6262   0.000069
715  6473   0.000074
541  6289   0.000078
888  6652   0.000080
776  6536   0.000081
696  6454   0.000082
699  6457   0.000103
827  6587   0.000111
923  6689   0.000113
284  6022   0.000115
460  6207   0.000115
902  6666   0.000119
275  6013   0.000122
41   5776   0.000125
649  6404   0.000128
818  6578   0.000129
968  6737   0.000133
607  6360   0.000138
378  6124   0.000139
114  5849   0.000141
169  5906   0.000143
905  6669   0.000159
722  6480   0.000163
961  6730   0.000167
..    ...        ...
756  6514   0.183373
986  6755   0.187499
743  6501   0.188000
711  6469   0.189221
322  6063   0.191154
730  6488   0.208586
908  6672   0.215906
384  6130   0.216294
587  6337   0.220241
879  6643   0.230314
136  5871   0.234509
952  6721   0.235887
967  6736   0.260476
411  6158   0.263258
248  5986   0.274987
47   5782   0.282559
204  5941   0.293871
682  6438   0.307539
977  6746   0.349886
59   5794   0.352012
122  5857   0.363759
979  6748   0.372231
140  5875   0.374176
7    5742   0.374801
843  6606   0.388608
58   5793   0.395327
807  6567   0.404119
116  5851   0.416563
163  5900   0.494107
385  6131   0.596250

[1000 rows x 2 columns]

In [43]:
result_pred_lt

       id      pred
57   5793  4.358161
115  5851  4.889107
162  5900  4.538356
383  6131  4.864043
802  6567  4.588478

In [44]:
# lt45_prob['pred'] = 4.5
# lt45_prob.drop('lt45_prob',axis=1,inplace=True)
# gt10_prob['pred'] = 10
# gt10_prob.drop('gt10_prob',axis=1,inplace=True)

In [45]:
lt45_prob
gt10_prob

       id  gt10_prob
928  6694   0.584416
846  6609   0.632801
398  6145   0.649063
973  6742   0.674975
628  6382   0.731662
601  6353   0.763137
33   5768   0.786636
292  6032   0.878746
938  6705   0.916191

In [46]:
submission = pd.concat([result_pred,result_pred_lt,result_pred_gt],axis=0)
submission.sort_values(by='id',inplace=True)
submission["pred"].to_csv('../submission/final_predict_result_stacking_21_2.csv',index=False, header=False)

In [47]:
submission["pred"].describe()

count    1000.000000
mean        5.720324
std         0.747028
min         4.358161
25%         5.264273
50%         5.570410
75%         5.998818
max        14.717699
Name: pred, dtype: float64